### PR TITLE
Keep Alive for server and client timing

### PR DESCRIPTION
**Pull request by roanrrmk**
Added server timing to keep alive calculation

### CODE REVIEW

**Comment by bertmelis** [comment]
You're sure you want to change all that?

**Comment by bertmelis** [comment]
I would do something like this

```
void MqttClient::_checkPing() {
  if (_keepAlive == 0) return;  // keepalive is disabled
  
  uint32_t currentMillis = millis();

  // disconnect when server was inactive for twice the keepalive time
  if (currentMillis - _lastServerActivity > 2000 * _keepAlive) {
    emc_log_w("Disconnecting, server exceeded keepalive");
    _state = State::disconnectingTcp;
    return;
  }

  // send ping when client was inactive for 0.7 times the keepalive time
  // or when the server hasn't responded during the keepAlive time
  if ((currentMillis - _lastClientActivity > 700 * _keepAlive) ||
      (currentMillis - _lastServerActivity > _keepAlive)) {
    emc_log_i("Near keepalive, sending PING");
    if (!_addPacket(PacketType.PINGREQ)) {
      emc_log_e("Could not create PING packet");
    }
  }
}
```

**Comment by Pablo2048** [comment]
In case of modifying keepalive I want to ask for one simple change. According to MQTT 3.1.2 protocol specification the broker has to disconnect client when keepalive timeout is 1.5 times value set, so I think, that the `700` is too fast for sendig keepalive. I'm asking for this change because I'm using espMqttClient in GSM/PPP environment where this setting mean more data to be transferred.

**Comment by bertmelis** [comment]
@Pablo2048  Yes, but on the other hand the client is supposed to send at least one control packet in the keepalive window.

[MQTT-3.1.2-23]:

> It is the responsibility of the Client to ensure that the interval between Control Packets being sent does not exceed the Keep Alive value. In the absence of sending any other Control Packets, the Client MUST send a PINGREQ Packet

**Comment by roanrrmk** [comment]
After reviewing the spec, 
>If a Client does not receive a PINGRESP Packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server.
It seems that client side disconnects should only happen after a failure of the server to respond to a PINGREQ.

**Comment by bertmelis** [comment]
Well, my interpretation was that as long as the server is responding to whatever sort of packet, the client treats it as being OK. Only if there is no activity, we send a PING.

So on every valid response from the server, we reset the timer and not only when doing ping/pong.

In any case, you have overwritten the entire base source in the PR so that needs to be rectified anyway.

**Comment by roanrrmk** [comment]
I would interpret it as only starting the disconnect timer after sending a ping.  

That's my mistake, rushed through the modification and didn't check.  I won't be able to correct until I get home in about 6 hours.

**Comment by bertmelis** [comment]
> I would interpret it as only starting the disconnect timer after sending a ping.

I want to keep the implementation as is for now (except your bugfix). The spec only specifies that the client **must** send at least 1 control packet within the keep alive window. And when an answer is expected, the broker **must** respond (even when for example a PUBLISH is not allowed) or close the connection. So as long as the broker responds we know it is alive (and so is the network connection). There is imo no need to send an extra PING to assess.

> That's my mistake, rushed through the modification and didn't check. I won't be able to correct until I get home in about 6 hours.

No worries. I can do it too, but I'll let you have the honours of the bugfix.

**Comment by roanrrmk** [comment]
I'm still learning git, hopefully I managed to get everything squared away. 

@bertmelis Thanks for your help!

**Comment by Pablo2048** [comment]
> 
> [MQTT-3.1.2-23]:
> 
> > It is the responsibility of the Client to ensure that the interval between Control Packets being sent does not exceed the Keep Alive value. In the absence of sending any other Control Packets, the Client MUST send a PINGREQ Packet
> 
> Would `900 *` be better?

You are right indeed, but when you take a look to other implementations (pubsubclient, or even paho - https://github.com/eclipse/paho.mqtt.python/blob/9782ab81fe7ee3a05e74c7f3e1d03d5611ea4be4/src/paho/mqtt/client.py#L2541 ) they all uses just keepalive as timeout. That is the reason why I ask for change to just keepalive. Anyway the `900` or `950` would be better...

**Comment by bertmelis** [comment]
> You are right indeed, but when you take a look to other implementations (pubsubclient, or even paho - https://github.com/eclipse/paho.mqtt.python/blob/9782ab81fe7ee3a05e74c7f3e1d03d5611ea4be4/src/paho/mqtt/client.py#L2541 ) they all uses just keepalive as timeout. That is the reason why I ask for change to just keepalive. Anyway the `900` or `950` would be better...

I never investigated other implementations, just copied from async mqtt client. Mosquitto broker disconnects are 1.5 times keepalive. So maybe it is safe to set it to keepalive. I'll put it to keepalive, saves a few instructions. (will be a separate commit)

Mosquitto:
https://github.com/eclipse/mosquitto/blob/efef2abdce58e131c34fa5312e62fa136364b8d6/src/keepalive.c#L49

**Pull request merged**
