### PR TITLE
fix _onPubcomp

### PR DESCRIPTION
**Pull request by MichaelDvP**
With receiving Pubcomp the communicaion is finished.

### CODE REVIEW

**Comment by bertmelis** [comment]
Another bug? 😢

**Comment by bertmelis** [comment]
Ouch, that's a stupid copy-paste error of me.

Obviously we don't need to send a pubcomp when receiving a pubcomp. 🤦

**Comment by MichaelDvP** [comment]
BTW: is this: https://github.com/bertmelis/espMqttClient/blob/490a94ab25e994dfe4905ffc0a155d0257ade404/src/MqttClient.cpp#L44 fixed value for _timeout intended or should it be EMC_TX_TIMEOUT from the config?

**Comment by bertmelis** [comment]
> BTW: is this:
> 
> https://github.com/bertmelis/espMqttClient/blob/490a94ab25e994dfe4905ffc0a155d0257ade404/src/MqttClient.cpp#L44
> 
> fixed value for _timeout intended or should it be EMC_TX_TIMEOUT from the config?

Yes. I believe so. This compile time variable also isn't in the docs.

**Comment by bertmelis** [comment]
The code was actually tested for this scenario but Mosquitto is forgiving and doesn't disconnect.

See https://github.com/bertmelis/espMqttClient/blob/main/test/test_client_native/test_client_native.cpp#L226

Maybe I should add a delay in the test to give Mosquitto some time to realize something went wrong...???

**Comment by MichaelDvP** [comment]
> Maybe I should add a delay in the test to give Mosquitto some time to realize something went wrong...???

No, mosquitto just knows the communication is successfull and ignores the extra pubcomp. There is no errormessage, it just works. 
Other brokers get confused by this packet. The ioBroker-mqtt i've used does not like it, i tested with mosquitto, it works, so i first thought it was an error in ioBroker,

**Comment by bertmelis** [comment]
That's it! I just test with Mosquitto (in Github actions but also in my home setup).

Thanks for the find!

**Pull request merged**
